/*
 * This file was generated by the Gradle 'init' task.
 * For more details, see:
 * https://docs.gradle.org/9.0.0/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Guava library (replace version as needed)
    implementation("com.google.guava:guava:31.1-jre")

    // OkHttp HTTP client
    implementation("com.squareup.okhttp3:okhttp:4.10.0")

    // JUnit 4 for testing
    testImplementation("junit:junit:4.13.2")
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            // Use JUnit 4 test framework
            useJUnit()
        }
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("org.example.App")
}
